logo_src: ''
logo_href: /
og_image: /uploads/image-placeholder.daj0efyq_29eycw.webp
logo_text: Personal Shopper
logo_alt: Personal Shopper

header_cta_text_en: Contact
header_cta_href_en: /en/contact
footer_description_en: Personal shopping and styling services in Canada.

header_cta_text_es: Contacto
header_cta_href_es: /es/contact
footer_description_es: Servicios de personal shopper en Canad√°.

header_cta_text_fr: Contact
header_cta_href_fr: /fr/contact
footer_description_fr: Services de personal shopper au Canada.
